version: "3"
services:
  redis:
    image: "redis:alpine"
    volumes:
      - ./data/redis:/data

  counter:
    image: "ghcr.io/soxft/time-counter:latest"
    ports:
      - "8080:8080"
    volumes:
      - ./data/counter:/app/expose
    links:
      - redis
    depends_on:
      - redis
    environment:
      LOG_ENABLE: true
      DEBUG_ENABLE: false
      REDIS_ADDR: redis:6379
      REDIS_PWD:
      REDIS_DATABASE: 1
      REDIS_PREFIX: tc
      API_SERVER: http:\/\/127.0.0.1:8080\/counter
      INTERVAL: 10
